//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankProcesses
    {
        public int BankProcessId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> ProcessTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual ProcessTypes ProcessTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual Banks Banks1 { get; set; }
        public virtual ProcessTypes ProcessTypes1 { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
