//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int BillId { get; set; }
        public string BillTitle { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<int> BillPeriodId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BankId { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual BillPeriods BillPeriods { get; set; }
        public virtual BillPeriods BillPeriods1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
