//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spendings
    {
        public int SpendingId { get; set; }
        public string SpendingTitle { get; set; }
        public Nullable<decimal> SpendingAmount { get; set; }
        public Nullable<System.DateTime> SpendingDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BankId { get; set; }
    
        public virtual Banks Banks { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Categories Categories1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
